// Mapping table for better component names
// You can easily edit these mappings to improve component naming
export const fileNameMappings: Record<string, string> = {
  // Popular tech companies and services
  githubactions: 'GithubActions',
  githubcopilot: 'GithubCopilot',
  githubpages: 'GithubPages',
  githubsponsors: 'GithubSponsors',
  stackoverflow: 'StackOverflow',
  stackblitz: 'StackBlitz',
  stackedit: 'StackEdit',
  stackexchange: 'StackExchange',
  stackhawk: 'StackHawk',
  stackshare: 'StackShare',

  // Programming languages and frameworks
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  reactjs: 'ReactJs',
  vuejs: 'VueJs',
  nextjs: 'NextJs',
  nuxtjs: 'NuxtJs',
  angularjs: 'AngularJs',
  nodejs: 'NodeJs',
  nodedotjs: 'NodeDotJs',

  // Databases
  postgresql: 'PostgreSQL',
  mongodb: 'MongoDB',

  // Google services
  googledrive: 'GoogleDrive',
  googlemaps: 'GoogleMaps',
  googlecloud: 'GoogleCloud',
  googleauthenticator: 'GoogleAuthenticator',
  googleadmob: 'GoogleAdMob',
  googleads: 'GoogleAds',
  googleadsense: 'GoogleAdSense',
  googleanalytics: 'GoogleAnalytics',
  googleappsscript: 'GoogleAppsScript',
  googleassistant: 'GoogleAssistant',
  googlebigquery: 'GoogleBigQuery',
  googlebigtable: 'GoogleBigTable',
  googlecalendar: 'GoogleCalendar',
  googlechat: 'GoogleChat',
  googlechrome: 'GoogleChrome',
  googleclassroom: 'GoogleClassroom',
  googlecontaineroptimizedos: 'GoogleContainerOptimizedOs',
  googledataflow: 'GoogleDataflow',
  googledataproc: 'GoogleDataproc',
  googledocs: 'GoogleDocs',
  googleearth: 'GoogleEarth',
  googleearthengine: 'GoogleEarthEngine',
  googlefit: 'GoogleFit',
  googlefonts: 'GoogleFonts',
  googleforms: 'GoogleForms',
  googlegemini: 'GoogleGemini',
  googlehome: 'GoogleHome',
  googlekeep: 'GoogleKeep',
  googlelens: 'GoogleLens',
  googlemeet: 'GoogleMeet',
  googlemessages: 'GoogleMessages',
  googlenearby: 'GoogleNearby',
  googlenews: 'GoogleNews',
  googlephotos: 'GooglePhotos',
  googleplay: 'GooglePlay',
  googlepubsub: 'GooglePubSub',
  googlescholar: 'GoogleScholar',
  googlesearchconsole: 'GoogleSearchConsole',
  googlesheets: 'GoogleSheets',
  googleslides: 'GoogleSlides',
  googlestreetview: 'GoogleStreetView',
  googlesummerofcode: 'GoogleSummerOfCode',
  googletagmanager: 'GoogleTagManager',
  googletasks: 'GoogleTasks',
  googletranslate: 'GoogleTranslate',
  googletv: 'GoogleTv',

  // Microsoft services
  microsoft: 'Microsoft',
  microsoftoffice: 'MicrosoftOffice',
  visualstudio: 'VisualStudio',
  visualstudiocode: 'VisualStudioCode',

  // AWS services
  amazonaws: 'AmazonWebServices',

  // App stores
  appstore: 'AppStore',
  playstore: 'PlayStore',

  // Social media
  linkedin: 'LinkedIn',
  youtube: 'YouTube',
  youtubegaming: 'YouTubeGaming',
  youtubekids: 'YouTubeKids',
  youtubemusic: 'YouTubeMusic',
  youtubeshorts: 'YouTubeShorts',
  youtubestudio: 'YouTubeStudio',
  instagram: 'Instagram',
  facebook: 'Facebook',
  facebookgaming: 'FacebookGaming',
  facebooklive: 'FacebookLive',
  tiktok: 'TikTok',
  snapchat: 'Snapchat',
  pinterest: 'Pinterest',
  reddit: 'Reddit',

  // Other popular services
  netflix: 'Netflix',
  spotify: 'Spotify',
  airbnb: 'Airbnb',
  firebase: 'Firebase',

  // Tech compound words
  appwrite: 'AppWrite',
  appsmith: 'AppSmith',
  appsignal: 'AppSignal',
  appgallery: 'AppGallery',
  codepen: 'CodePen',
  codeclimate: 'CodeClimate',
  codecov: 'CodeCov',
  codesandbox: 'CodeSandbox',
  codeberg: 'CodeBerg',
  webassembly: 'WebAssembly',
  webstorm: 'WebStorm',
  devpost: 'DevPost',
  deviant: 'DeviantArt',
  devto: 'DevTo',
  apifox: 'ApiFox',
  apikey: 'ApiKey',

  // Data and Cloud services
  datadog: 'DataDog',
  databricks: 'DataBricks',
  datacamp: 'DataCamp',
  datastax: 'DataStax',
  cloudflare: 'Cloudflare',
  cloudsmith: 'CloudSmith',
  icloud: 'iCloud',
  soundcloud: 'SoundCloud',
  mixcloud: 'MixCloud',

  // Authentication and Security
  authzero: 'AuthZero',
  auth0: 'Auth0',
  okta: 'Okta',
  onelogin: 'OneLogin',
  twofa: 'TwoFA',

  // Payment and Commerce
  paypal: 'PayPal',
  patreon: 'Patreon',
  klarna: 'Klarna',
  razorpay: 'RazorPay',
  applepay: 'ApplePay',
  googlepay: 'GooglePay',
  amazonpay: 'AmazonPay',

  // Streaming and Media
  streamdeck: 'StreamDeck',
  streamlabs: 'StreamLabs',
  streamlit: 'StreamLit',
  airplay: 'AirPlay',
  chromecast: 'ChromeCast',
  plex: 'Plex',
  emby: 'Emby',
  jellyfin: 'Jellyfin',

  // Version Control and DevOps
  bitbucket: 'BitBucket',
  bitrise: 'BitRise',
  gitlab: 'GitLab',
  gitbook: 'GitBook',
  gitea: 'Gitea',
  giteaactions: 'GiteaActions',
  jenkins: 'Jenkins',
  teamcity: 'TeamCity',
  circleci: 'CircleCI',
  travisci: 'TravisCI',

  // Blockchain and Crypto
  coinbase: 'CoinBase',
  blockchain: 'BlockChain',
  ethereum: 'Ethereum',
  bitcoin: 'BitCoin',
  litecoin: 'LiteCoin',
  dogecoin: 'DogeCoin',
  metamask: 'MetaMask',
  opensea: 'OpenSea',

  // CMS and Website Builders
  wordpress: 'WordPress',
  drupal: 'Drupal',
  joomla: 'Joomla',
  webflow: 'WebFlow',
  squarespace: 'Squarespace',
  wix: 'Wix',
  shopify: 'Shopify',
  magento: 'Magento',

  // Communication and Social
  whatsapp: 'WhatsApp',
  telegram: 'Telegram',
  discord: 'Discord',
  teamspeak: 'TeamSpeak',
  skype: 'Skype',
  zoom: 'Zoom',
  slack: 'Slack',
  mattermost: 'Mattermost',

  // Design and Creative
  figma: 'Figma',
  sketch: 'Sketch',
  framer: 'Framer',
  invision: 'InVision',
  zeplin: 'Zeplin',
  canva: 'Canva',
  behance: 'Behance',
  dribbble: 'Dribbble',

  // Special cases with underscores or special characters
  uniqlo_ja: 'UniqloJa',
  rainyun: 'RainYun',
  visualparadigm: 'VisualParadigm',
  weread: 'WeRead',
  deepmind: 'DeepMind',
  freshrss: 'FreshRSS',
  backstagecasting: 'BackstageCasting',
  handshakeprotocol: 'HandshakeProtocol',
  hiveblockchain: 'HiveBlockchain',
  springcreators: 'SpringCreators',

  // Add more mappings as needed...
  // Tip: Use PascalCase for compound words, e.g., 'compoundword': 'CompoundWord'
};
