name: Build tabler-icons

on:
  workflow_dispatch:

jobs:
  tabler-icons:
    name: Build tabler-icons
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        shell: bash

      - name: Build tabler-icons
        run: npx nx run tabler-icons:build:production --skip-nx-cache
        shell: bash
