name: Generate icons

on:
  workflow_dispatch:

jobs:
  generate-icons:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: ['20']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm i

      - name: Build nx-generators
        run: npx nx build nx-generators

      - run: npx nx generate @semantic-icons/nx-generators:heroicons
      - run: npx nx generate @semantic-icons/nx-generators:tabler-icons
      - run: npx nx generate @semantic-icons/nx-generators:flowbite-icons
      - run: npx nx generate @semantic-icons/nx-generators:flag-icons
      - run: npx nx generate @semantic-icons/nx-generators:lucide-icons
      - run: npx nx generate @semantic-icons/nx-generators:circle-flags
      - run: npx nx generate @semantic-icons/nx-generators:bootstrap-icons
      - run: npx nx generate @semantic-icons/nx-generators:lineicons
      - run: npx nx generate @semantic-icons/nx-generators:simple-icons

      - name: Setup Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          [[ $(git status --porcelain) ]] && git commit -m "build: generate icons" || echo "nothing to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
