name: Publish a package

on:
  workflow_dispatch:
    inputs:
      t_option:
        type: choice
        description: t option
        options:
          - lucide-icons
          - lucide-lab-icons
          - simple-icons
          - fontawesome
  # schedule:
  #   - cron: '0 4 * * *'

  push:
    tags:
      - v*.*.*

jobs:
  publish-package:
    name: Publish a package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Version
        run: npx nx release version minor -p ${{ github.event.inputs.t_option }}
        shell: bash

      - name: Build projects
        run: npx nx run-many --target=build --projects=${{ github.event.inputs.t_option }}
        shell: bash
        env:
          NODE_OPTIONS: --max_old_space_size=8192

      - name: Publish packages
        run: npx nx release publish -p ${{ github.event.inputs.t_option }}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Setup Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          [[ $(git status --porcelain) ]] && git commit -m "build: publish package ${{ github.event.inputs.t_option }}" || echo "nothing to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
