name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

          # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - name: Run command and capture output
        id: get_output
        run: |
          # Run your command and save the output to a variable
          output=$(nx show projects --affected -t nx-release-publish --sep=,)
          echo "Command Output: $output"
          echo "::set-output name=result::$output"

      - name: Use the output
        run: |
          echo "Captured Output: ${{ steps.get_output.outputs.result }}"
